sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Ljf20031227
  reids:
    host: localhost
    port: 6379
    password: Ljf20031227
    datebase: 10
  alioss:
    endpoint: 告訴對方
    access-key-id: 受到廣汎
    access-key-secret: 士大夫敢死隊風格
    bucket-name: 歲的法國
