sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Ljf20031227
  reids:
    host: localhost
    port: 6379
    password: Ljf20031227
    datebase: 10
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tFh5MdcFDXJmQo1vNNo
    access-key-secret: hFxM4w6SL2EA6SrIKIEVyUmcWQoToE
    bucket-name: modestggb
  wechat:
    appid: wx12b66057dae5aa1d
    secret: fb9c91dc94adf68880c4d8b8efbc22ff
    mchid:                 #   1561414331
    mchSerialNo:           #  4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath:    #   D:\pay\apiclient_key.pem
    apiV3Key:              #   CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: #   D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl:             #   https://58869fb.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl:       #   https://58869fb.r2.cpolar.top/notify/refundSuccess