sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Ljf20031227
  reids:
    host: localhost
    port: 6379
    password: Ljf20031227
    datebase: 10
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tFh5MdcFDXJmQo1vNNo
    access-key-secret: hFxM4w6SL2EA6SrIKIEVyUmcWQoToE
    bucket-name: modestggb
  wechat:
    appid: wx12b66057dae5aa1d
    secret: fb9c91dc94adf68880c4d8b8efbc22ff
    mchid:
    mch-serial-no:
    private-key-file-path:
    api-v3-key:
    we-chat-pay-cert-file-path:
    notify-url:
    refund-notify-url: